name: CI
run-name: Build Vite Application
on: [push]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: Update config
        run: |
          git config --global user.email "csperando@gmail.com"
          git config --global user.name "Coleman Sperando"

      - name: Build dist/ directory
        run: |
          echo "${{  github.repository }} cloned"
          cd explore
          npm install
          npm run build

      - name: Force commit updated dist
        run: |
          git add dist -f
          git commit -m "actions automated commit build dist/"

      - name: Push dist
        run: |
          git push origin main --force
